<?php
return [
    'db'=>[
        'class' => 'yii\db\Connection',  
        'dsn' => 'mysql:host=localhost;dbname=eulims',
        'username' => 'eulims',
        'password' => 'eulims',
        //'username'=>'arisro9',
        //'password'=>'qwerty!@#$%', 
        'charset' => 'utf8',
        'tablePrefix' => 'tbl_',
    ],
    'labdb'=>[
        'class' => 'yii\db\Connection',  
        'dsn' => 'mysql:host=localhost;dbname=eulims_lab',
        'username' => 'eulims',
        'password' => 'eulims',
        //'username'=>'arisro9',
        //'password'=>'qwerty!@#$%', 
        'charset' => 'utf8',
        'tablePrefix' => 'tbl_',
    ],
    'inventorydb'=>[
        'class' => 'yii\db\Connection',  
        'dsn' => 'mysql:host=localhost;dbname=eulims_inventory',
        'username' => 'eulims',
        'password' => 'eulims',
        //'username'=>'arisro9',
        //'password'=>'qwerty!@#$%', 
        'charset' => 'utf8',
        'tablePrefix' => 'tbl_',
    ],
    'financedb'=>[
        'class' => 'yii\db\Connection',  
        'dsn' => 'mysql:host=localhost;dbname=eulims_finance',
        'username' => 'eulims',
        'password' => 'eulims',
        //'username'=>'arisro9',
        //'password'=>'qwerty!@#$%', 
        'charset' => 'utf8',
        'tablePrefix' => 'tbl_',
    ],
    'addressdb'=>[
        'class' => 'yii\db\Connection',  
        'dsn' => 'mysql:host=localhost;dbname=eulims_address',
        'username' => 'eulims',
        'password' => 'eulims',
        //'username'=>'arisro9',
        //'password'=>'qwerty!@#$%', 
        'charset' => 'utf8',
        'tablePrefix' => 'tbl_',
    ],
    'referraldb'=>[
        'class' => 'yii\db\Connection',  
        'dsn' => 'mysql:host=localhost;dbname=eulims_referral_lab',
        'username' => 'eulims',
        'password' => 'eulims',
        //'username'=>'arisro9',
        //'password'=>'qwerty!@#$%', 
        'charset' => 'utf8',
        'tablePrefix' => 'tbl_',
    ],
];